In [3]:
#implement svm regression using advertising dataset
import pandas as pd
dataset = pd.read_csv('./Advertising.csv')
dataset.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [4]:
X = dataset.iloc[:,:-1] 
Y = dataset.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=100)

In [5]:
from sklearn.svm import SVR
m_r=SVR(kernel='linear')
m_r.fit(X_train,Y_train)
Y_pred=m_r.predict(X_test)

In [6]:
D=pd.DataFrame({'actual Value': Y_test, 'Predicted Value': Y_pred})
D.head()

     actual Value  Predicted Value
126           6.6         9.460996
104          20.7        20.837512
99           17.2        16.503599
92           19.4        20.102189
111          21.8        21.575688