In [1]:
import pandas as pd
dataset = pd.read_csv("/content/Advertising.csv")
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]
dataset.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 100)

In [3]:
from sklearn.svm import SVR
Re = SVR(kernel='linear')
Re.fit(x_train, y_train)
y_pred= Re.predict(x_test)

In [4]:
diff=pd.DataFrame({'actual Value': y_test, 'Predicted Value': y_pred})
diff.head()

     actual Value  Predicted Value
126           6.6         9.739764
104          20.7        21.227867
99           17.2        16.844163
92           19.4        20.249921
111          21.8        21.949661